version: '3.8'

services:
  backend:
    build: ./memora-backend
    container_name: memora-backend-container
    ports:
      - "3001:3001"
    env_file:
      - ./memora-backend/.env
    restart: always

  frontend:
    build: ./memora-frontend
    container_name: memora-frontend-container
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
