import { formatDateDDMMYYYY, formatDateWithWeekday } from '../utils/dateFormat';

const getLocalDateString = (value = new Date()) => {
  if (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return value;
  }

  const date = value instanceof Date ? value : new Date(value);
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');

  return `${year}-${month}-${day}`;
};

const parseStoredJson = (value, fallback) => {
  if (!value) return fallback;

  try {
    return JSON.parse(value);
  } catch {
    return fallback;
  }
};

const defaultJournalTemplates = {
  daily: `# Learning Journal - {{dateLabel}}

## Overview
- Topics reviewed: {{topicCount}}
- Focus sessions: {{focusSessions}}
- Study time: {{studyTime}} minutes

## Activities
{{activities}}

## Goals
- What do I want to complete today?
- What is the most important thing to learn?

## Reflection
- What went well today?
- What was difficult?
- What should I revisit tomorrow?

## Habits
- Which habit did I keep?
- Which habit needs attention?

## Notes
- Add anything important here.

---
Auto-generated by Memora`,
  weekly: `# Weekly Summary - {{weekRange}}

## Overview
- Active study days: {{activeDays}} out of 7
- Average topics per day: {{avgTopicsPerDay}}
- Average study time per day: {{avgStudyTimePerDay}} minutes
- Most productive day: {{mostProductiveDay}}

## Study Summary
- Topics reviewed: {{totalTopics}}
- Focus sessions: {{totalFocusSessions}}
- Total study time: {{totalStudyTime}} minutes

## Daily Breakdown
{{dailyBreakdown}}

## Topics Studied
{{topicsSummary}}

## Goals
- Which topics need more attention?
- How can I improve my study routine?

## Reflection
- What did I learn this week?
- What challenged me?
- What should I repeat next week?

## Habits
- Which habits were consistent?
- Which habits need work?

## Notes
- Add anything important here.

---
{{summaryFooter}}`,
  monthly: `# Monthly Summary - {{monthName}}

## Overview
- Active study days: {{activeDays}} out of {{daysInMonth}}
- Topics reviewed: {{totalTopics}}
- Focus sessions: {{totalFocusSessions}}
- Total study time: {{totalStudyTime}} minutes

## Topics Studied
{{topicsSummary}}

## Goals
- What are my learning priorities for next month?
- Which topics need deeper exploration?

## Reflection
- What were my biggest learning achievements this month?
- What topics or concepts did I struggle with?
- What patterns do I notice in my study habits?

## Habits
- Which habits helped me the most?
- What should I improve next month?

## Notes
- Add anything important here.

---
{{summaryFooter}}`
};

const mergeJournalTemplates = (templates = {}) => ({
  daily: templates.daily || defaultJournalTemplates.daily,
  weekly: templates.weekly || defaultJournalTemplates.weekly,
  monthly: templates.monthly || defaultJournalTemplates.monthly
});

const renderJournalTemplate = (template, values = {}) => {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const value = values[key];
    return value === undefined || value === null ? '' : String(value);
  });
};

class JournalService {
  constructor() {
    this.activities = [];
    this.settings = this.loadSettings();
    this.currentUserId = null;
    this.dailyPushTimeoutId = null;
    this.pushRetryTimeoutId = null;
  }

  resolveUserStorageId(userOrId) {
    if (!userOrId) return null;

    if (typeof userOrId === 'object') {
      const objectId = userOrId.id || userOrId._id || userOrId.email || null;
      return objectId ? String(objectId) : null;
    }

    return String(userOrId);
  }

  migrateLegacyStorageForUser(resolvedUserId) {
    if (!resolvedUserId) return;

    const userSettingsKey = `journalSettings_${resolvedUserId}`;
    const legacySettings = localStorage.getItem('journalSettings');
    const currentSettings = localStorage.getItem(userSettingsKey);

    if (!currentSettings && legacySettings) {
      localStorage.setItem(userSettingsKey, legacySettings);
    }

    for (let index = 0; index < localStorage.length; index += 1) {
      const key = localStorage.key(index);
      if (!key) continue;

      if (!/^(activities|journal)_\d{4}-\d{2}-\d{2}$/.test(key)) {
        continue;
      }

      const userScopedKey = `${key}_${resolvedUserId}`;
      if (localStorage.getItem(userScopedKey)) continue;

      const value = localStorage.getItem(key);
      if (value === null) continue;
      localStorage.setItem(userScopedKey, value);
    }
  }

  // Set current user for user-specific storage
  setCurrentUser(userOrId) {
    const resolvedUserId = this.resolveUserStorageId(userOrId);
    if (!resolvedUserId) {
      console.warn('📝 Journal: Could not resolve user id, keeping previous user context');
      return;
    }

    this.migrateLegacyStorageForUser(resolvedUserId);

    this.currentUserId = resolvedUserId;
    this.settings = this.loadSettings(); // Reload settings for this user
  }

  // Get user-specific localStorage key
  getUserStorageKey(key) {
    return this.currentUserId ? `${key}_${this.currentUserId}` : key;
  }

  loadSettings() {
    const key = this.getUserStorageKey('journalSettings');
    const saved = localStorage.getItem(key);
    const defaultSettings = {
      autoJournal: true, // Enable by default for better UX
      autoPush: false,
      githubRepo: '',
      githubToken: '',
      journalFormat: 'markdown',
      dailyPushTime: '23:59',
      journalTemplates: mergeJournalTemplates()
    };

    const storedSettings = saved ? parseStoredJson(saved, {}) : {};
    return {
      ...defaultSettings,
      ...storedSettings,
      journalTemplates: mergeJournalTemplates(storedSettings.journalTemplates || defaultSettings.journalTemplates)
    };
  }

  saveSettings(settings) {
    this.settings = {
      ...settings,
      journalTemplates: mergeJournalTemplates(settings.journalTemplates || this.settings.journalTemplates)
    };
    localStorage.setItem(this.getUserStorageKey('journalSettings'), JSON.stringify(this.settings));

    if (!this.settings.autoPush) {
      this.clearPushSchedules();
    }
  }

  clearPushSchedules() {
    if (this.dailyPushTimeoutId) {
      clearTimeout(this.dailyPushTimeoutId);
      this.dailyPushTimeoutId = null;
    }

    if (this.pushRetryTimeoutId) {
      clearTimeout(this.pushRetryTimeoutId);
      this.pushRetryTimeoutId = null;
    }
  }

  getJournalTemplates() {
    return mergeJournalTemplates(this.settings.journalTemplates);
  }

  // Log different types of activities
  logTopicAdded(topic) {
    if (!this.currentUserId) {
      console.warn('📝 Journal: No user set, skipping activity log');
      return;
    }

    this.addActivity(`Added topic: "${topic.title}" (Difficulty: ${topic.difficulty}/5)`);
  }

  logTopicReviewed(topic, performance) {
    if (!this.currentUserId) {
      console.warn('📝 Journal: No user set, skipping activity log');
      return;
    }

    const performanceText = performance === 'easy' ? 'Easy' :
                 performance === 'good' ? 'Good' :
                 performance === 'hard' ? 'Hard' : 'Failed';

    const topicTitle = topic?.title || 'Unknown Topic';
    const topicDesc = topic?.content ? ` (${topic.content.substring(0, 50)}${topic.content.length > 50 ? '...' : ''})` : '';

    this.addActivity(`Reviewed "${topicTitle}"${topicDesc} - ${performanceText}`);
  }

  logTopicSkipped(topic) {
    const topicTitle = topic?.title || 'Unknown Topic';
    const topicDesc = topic?.content ? ` (${topic.content.substring(0, 50)}${topic.content.length > 50 ? '...' : ''})` : '';

    this.addActivity(`Skipped "${topicTitle}"${topicDesc} - will review later`);
  }

  logTopicDeleted(topic) {
    const topicTitle = topic?.title || 'Unknown Topic';
    const topicDesc = topic?.content ? ` (${topic.content.substring(0, 50)}${topic.content.length > 50 ? '...' : ''})` : '';

    this.addActivity(`Deleted "${topicTitle}"${topicDesc}`);
  }

  logTopicEdited(originalTopic, updatedData) {
    const topicTitle = originalTopic?.title || updatedData?.title || 'Unknown Topic';
    const changes = [];

    if (originalTopic?.title !== updatedData?.title) {
      changes.push(`title: "${originalTopic?.title}" → "${updatedData?.title}"`);
    }
    if (originalTopic?.difficulty !== updatedData?.difficulty) {
      changes.push(`difficulty: ${originalTopic?.difficulty} → ${updatedData?.difficulty}`);
    }

    const changeText = changes.length > 0 ? ` (${changes.join(', ')})` : '';
    this.addActivity(`Edited "${topicTitle}"${changeText}`);
  }

  logDailySessionStart() {
    const today = getLocalDateString();
    const sessionKey = `session_logged_${today}`;

    // Only log once per day
    if (!localStorage.getItem(sessionKey)) {
      this.addActivity('Started learning session');
      localStorage.setItem(sessionKey, 'true');
    }
  }

  logMemScoreEvaluation(results) {
    const score = results.overallScore || 0;
    this.addActivity(`Completed MemScore evaluation - Score: ${score.toFixed(1)}/10`);
  }

  logChronicleEventCreated(eventData = {}) {
    const title = String(eventData.title || '').trim() || 'Untitled event';
    const eventType = String(eventData.type || 'event').trim();
    const eventDate = eventData.date ? new Date(eventData.date) : null;
    const isValidDate = eventDate instanceof Date && !Number.isNaN(eventDate.getTime());
    const dateLabel = isValidDate ? formatDateDDMMYYYY(eventDate) : 'unknown date';

    this.addActivity(`Created chronicle ${eventType} "${title}" on ${dateLabel}`);
  }

  logMindmapCreated(mindmap = {}, source = 'manual') {
    const title = String(mindmap.title || '').trim() || 'Untitled mindmap';
    if (source === 'ai') {
      this.addActivity(`Generated AI mindmap: "${title}"`);
      return;
    }

    this.addActivity(`Created mindmap: "${title}"`);
  }

  logDocTagResourceCreated(resource = {}) {
    const title = String(resource.name || resource.title || '').trim() || 'Untitled resource';
    this.addActivity(`Added DocTags resource: "${title}"`);
  }

  logFocusSession(duration, topicsStudied = []) {
    const minutes = Math.round(duration / 60000); // Convert ms to minutes
    let activity = `Focus session: ${minutes} minutes`;

    if (topicsStudied.length > 0) {
      const cleanedTopics = topicsStudied
        .map((topic) => String(topic || '').trim())
        .filter(Boolean);

      if (cleanedTopics.length === 1) {
        activity += ` (Topic: ${cleanedTopics[0]})`;
      } else if (cleanedTopics.length > 1) {
        activity += ` (${cleanedTopics.length} topics: ${cleanedTopics.join(', ')})`;
      }
    }

    this.addActivity(activity);
  }

  logStudyStreak() {
    // Study streak logging disabled - was causing too many duplicate entries
    return;
  }

  logMemScoreUpdate(oldScore, newScore) {
    if (!this.settings.autoJournal) return;
    
    const change = newScore - oldScore;
    const changeText = change > 0 ? `+${change.toFixed(1)}` : change.toFixed(1);
    
    this.addActivity(`MemScore updated: ${oldScore.toFixed(1)} -> ${newScore.toFixed(1)} (${changeText})`);
  }

  logTaskAdded(task, count = 1) {
    const title = String(task?.title || '').trim() || 'Untitled task';
    const quantity = Number(count) || 1;
    const typeLabel = String(task?.taskType || '').toLowerCase().includes('recurring') ? 'habit' : 'task';

    if (quantity > 1) {
      this.addActivity(`Added ${quantity} ${typeLabel} entries for "${title}"`);
      return;
    }

    this.addActivity(`Added ${typeLabel}: "${title}"`);
  }

  logTaskCompletion(task, completed) {
    const title = String(task?.title || '').trim() || 'Untitled task';
    const isHabit = String(task?.taskType || '').toLowerCase().includes('recurring');
    const noun = isHabit ? 'Habit' : 'Task';
    const status = completed ? 'completed' : 'marked pending';
    this.addActivity(`${noun} ${status}: "${title}"`);
  }

  logTaskDeleted(task, scope = 'single') {
    const title = String(task?.title || '').trim() || 'Untitled task';
    const isHabit = String(task?.taskType || '').toLowerCase().includes('recurring');

    if (isHabit && scope === 'series') {
      this.addActivity(`Deleted full habit series: "${title}"`);
      return;
    }

    this.addActivity(`Deleted ${isHabit ? 'habit occurrence' : 'task'}: "${title}"`);
  }

  logTaskEdited(beforeTask, afterTask) {
    const previousTitle = String(beforeTask?.title || '').trim();
    const nextTitle = String(afterTask?.title || '').trim();
    const resolvedTitle = nextTitle || previousTitle || 'Untitled task';
    this.addActivity(`Edited task: "${resolvedTitle}"`);
  }

  logHabitSeriesExtended(task, addedCount = 0) {
    const title = String(task?.title || '').trim() || 'Untitled habit';
    const count = Number(addedCount) || 0;
    this.addActivity(`Extended habit for another 3 months: "${title}" (${count} new entries)`);
  }

  addActivity(activityText) {
    if (!this.currentUserId) {
      console.warn('📝 Journal: No user set, cannot add activity');
      return;
    }

    const today = getLocalDateString();
    const timestamp = new Date().toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });

    const activity = `[${timestamp}] ${activityText}`;

    // Get today's activities
    const todayActivities = this.getTodayActivities();

    // Check for duplicates to avoid spam
    const isDuplicate = todayActivities.some(existingActivity =>
      existingActivity.includes(activityText.substring(0, 50))
    );

    if (isDuplicate) {
      return;
    }

    todayActivities.push(activity);

    // Save to localStorage with user-specific key
    localStorage.setItem(this.getUserStorageKey(`activities_${today}`), JSON.stringify(todayActivities));

    window.dispatchEvent(new CustomEvent('journalActivitiesUpdated', {
      detail: { date: today, activities: todayActivities }
    }));

    // Update journal entry only if auto-journal is enabled
    if (this.settings.autoJournal) {
      this.updateJournalEntry();
    }
  }

  getTodayActivities() {
    const today = getLocalDateString();
    const saved = localStorage.getItem(this.getUserStorageKey(`activities_${today}`));
    return parseStoredJson(saved, []);
  }

  updateJournalEntry() {
    if (!this.settings.autoJournal) {
      return;
    }

    const today = getLocalDateString();
    const activities = this.getTodayActivities();

    const storageKey = this.getUserStorageKey(`journal_${today}`);
    const existingEntry = localStorage.getItem(storageKey);
    const hasExistingManualEntry = typeof existingEntry === 'string' && existingEntry.trim().length > 0;

    // Do not overwrite user-authored entries when activities change.
    const journalEntry = hasExistingManualEntry
      ? existingEntry
      : this.generateInitialEntry(today, activities);

    if (!hasExistingManualEntry) {
      // Save auto-generated entry only when one does not already exist.
      localStorage.setItem(storageKey, journalEntry);
    }

    // Trigger a custom event to notify the Journal component
    window.dispatchEvent(new CustomEvent('journalUpdated', {
      detail: { date: today, content: journalEntry, activities }
    }));
  }

  calculateTotalStudyTime(activities) {
    let totalMinutes = 0;
    
    activities.forEach(activity => {
      const match = activity.match(/Focus session: (\d+) minutes/);
      if (match) {
        totalMinutes += parseInt(match[1]);
      }
    });
    
    return totalMinutes;
  }

  buildActivitySections(activities = []) {
    const rows = (Array.isArray(activities) ? activities : [])
      .map((item) => String(item || '').trim())
      .filter(Boolean);

    const buckets = {
      topics: [],
      mindmaps: [],
      tasks: [],
      doctags: [],
      other: []
    };

    rows.forEach((activity) => {
      const normalized = activity.toLowerCase();

      if (normalized.includes('mindmap')) {
        buckets.mindmaps.push(activity);
        return;
      }

      if (normalized.includes('doctags resource') || normalized.includes('workspace docs')) {
        buckets.doctags.push(activity);
        return;
      }

      if (normalized.includes('task') || normalized.includes('chronicle')) {
        buckets.tasks.push(activity);
        return;
      }

      if (
        normalized.includes('reviewed "')
        || normalized.includes('added topic')
        || normalized.includes('edited "')
        || normalized.includes('skipped "')
        || normalized.includes('deleted "')
      ) {
        buckets.topics.push(activity);
        return;
      }

      buckets.other.push(activity);
    });

    const toSection = (title, sectionRows, emptyText) => {
      return [
        `### ${title}`,
        ...(sectionRows.length > 0 ? sectionRows.map((row) => `- ${row}`) : [`- ${emptyText}`])
      ].join('\n');
    };

    const sections = [
      toSection('Topics', buckets.topics, 'No topic activity logged yet'),
      toSection('Mindmaps', buckets.mindmaps, 'No mindmap activity logged yet'),
      toSection('Tasks', buckets.tasks, 'No task activity logged yet'),
      toSection('DocTags', buckets.doctags, 'No DocTags activity logged yet')
    ];

    if (buckets.other.length > 0) {
      sections.push(toSection('Other', buckets.other, 'No additional activity logged yet'));
    }

    return sections.join('\n\n');
  }

  generateInitialEntry(forDate = getLocalDateString(), activities = null) {
    const dateString = getLocalDateString(forDate);
    const displayDate = new Date(`${dateString}T00:00:00`);
    const dateLabel = formatDateWithWeekday(displayDate, 'long');

    const dayActivities = Array.isArray(activities) ? activities : this.getTodayActivities();

    const topicCount = dayActivities.filter(activity =>
      /Added topic|Added new topic|Reviewed "/.test(activity)
    ).length;

    const focusSessions = dayActivities.filter(activity =>
      /Focus session:/.test(activity)
    ).length;

    const totalStudyTime = this.calculateTotalStudyTime(dayActivities);

    const activitySection = this.buildActivitySections(dayActivities);

    return renderJournalTemplate(this.getJournalTemplates().daily, {
      dateLabel,
      topicCount,
      focusSessions,
      studyTime: totalStudyTime,
      activities: activitySection,
      weekRange: '',
      activeDays: '',
      avgTopicsPerDay: '',
      avgStudyTimePerDay: '',
      mostProductiveDay: '',
      dailyBreakdown: '',
      topicsSummary: '',
      summaryFooter: ''
    });
  }

  // GitHub integration
  async pushToGitHub(date = null) {
    if (!this.settings.githubRepo || !this.settings.githubToken) {
      throw new Error('GitHub repository and token must be configured');
    }

    if (!/^[-\w.]+\/[-\w.]+$/.test(this.settings.githubRepo.trim())) {
      throw new Error('GitHub repository format must be owner/repo');
    }

    const targetDate = date || getLocalDateString();
    const journalEntry = localStorage.getItem(this.getUserStorageKey(`journal_${targetDate}`));

    if (!journalEntry) {
      throw new Error(`No journal entry found for ${targetDate}`);
    }

    const fileName = `${targetDate}.md`;
    const content = btoa(unescape(encodeURIComponent(journalEntry))); // Base64 encode

    try {
      // Check if file exists
      const checkResponse = await fetch(
        `https://api.github.com/repos/${this.settings.githubRepo}/contents/${fileName}`,
        {
          headers: {
            'Authorization': `token ${this.settings.githubToken}`,
            'Accept': 'application/vnd.github.v3+json'
          }
        }
      );

      let sha = null;
      if (checkResponse.ok) {
        const fileData = await checkResponse.json();
        sha = fileData.sha;
      }

      // Create or update file
      const response = await fetch(
        `https://api.github.com/repos/${this.settings.githubRepo}/contents/${fileName}`,
        {
          method: 'PUT',
          headers: {
            'Authorization': `token ${this.settings.githubToken}`,
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            message: `Learning journal entry for ${targetDate}`,
            content: content,
            ...(sha && { sha })
          })
        }
      );

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.message || 'Failed to push to GitHub');
      }

      return await response.json();
    } catch (error) {
      console.error('GitHub push error:', error);
      throw error;
    }
  }

  // Schedule daily push
  scheduleDailyPush() {
    if (!this.settings.autoPush) return;

    if (this.dailyPushTimeoutId) {
      clearTimeout(this.dailyPushTimeoutId);
      this.dailyPushTimeoutId = null;
    }

    const now = new Date();
    const [hours, minutes] = this.settings.dailyPushTime.split(':');
    const pushTime = new Date();
    pushTime.setHours(parseInt(hours), parseInt(minutes), 0, 0);

    // If push time has passed today, schedule for tomorrow
    if (pushTime <= now) {
      pushTime.setDate(pushTime.getDate() + 1);
    }

    const timeUntilPush = pushTime.getTime() - now.getTime();

    this.dailyPushTimeoutId = setTimeout(async () => {
      try {
        await this.pushToGitHub();
        this.dailyPushTimeoutId = null;
        
        // Schedule next push
        this.scheduleDailyPush();
      } catch (error) {
        console.error('Failed to push daily journal:', error);
        this.dailyPushTimeoutId = null;
        
        // Retry in 1 hour
        if (this.pushRetryTimeoutId) {
          clearTimeout(this.pushRetryTimeoutId);
        }
        this.pushRetryTimeoutId = setTimeout(() => {
          this.pushRetryTimeoutId = null;
          this.scheduleDailyPush();
        }, 60 * 60 * 1000);
      }
    }, timeUntilPush);
  }

  // Initialize the service
  init() {
    this.clearPushSchedules();

    if (!this.settings.autoPush) return;

    this.scheduleDailyPush();
  }
}

// Create singleton instance
const journalService = new JournalService();

export default journalService;
